package com.example.dat.enums;

public enum Specialization {

    // Medicina Interna y Subespecialidades
    MEDICINA_INTERNA,
    CARDIOLOGIA,
    NEUMOLOGIA,
    GASTROENTEROLOGIA,
    NEFROLOGIA,
    ENDOCRINOLOGIA,
    REUMATOLOGIA,
    INFECTOLOGIA,
    HEMATOLOGIA,
    ONCOLOGIA_MEDICA,
    GERIATRIA,
    MEDICINA_FAMILIAR,
    INMUNOLOGIA,

    // Especialidades Clínicas Generales
    PEDIATRIA,
    NEUROLOGIA,
    DERMATOLOGIA,
    PSIQUIATRIA,
    OFTALMOLOGIA,
    OTORRINOLARINGOLOGIA,
    MEDICINA_FISICA_Y_REHABILITACION,
    MEDICINA_DE_DEPORTE,

    // Especialidades Quirúrgicas
    CIRUGIA_GENERAL,
    NEUROCIRUGIA,
    CIRUGIA_PLASTICA_RECONSTRUCTIVA,
    CIRUGIA_CARDIOVASCULAR,
    CIRUGIA_TORACICA,
    TRAUMATOLOGIA_Y_ORTOPEDIA,
    UROLOGIA,
    GINECOLOGIA_Y_OBSTETRICIA,
    CIRUGIA_PEDIATRICA,
    ANGIOLOGIA_Y_CIRUGIA_VASCULAR,
    CIRUGIA_MAXILOFACIAL,

    // Especialidades de Apoyo y Diagnóstico
    ANESTESIOLOGIA_Y_REANIMACION,
    RADIOLOGIA_O_IMAGENOLOGIA,
    ANATOMIA_PATOLOGICA,
    MEDICINA_DE_LABORATORIO,
    MEDICINA_NUCLEAR,
    MEDICINA_INTENSIVA,
    MEDICINA_DE_EMERGENCIAS,
    MEDICINA_PREVENTIVA,
    GENETICA_MEDICA,

    // Estomatología (Odontología)
    ODONTOLOGIA_GENERAL,
    ORTODONCIA,
    PERIODONCIA,
    ENDODONCIA

}
